blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed


app_name = 'blog'

urlpatterns = [
    # views de postagens
    path('', views.post_list, name='post_list'),
    # path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name="post_detail"),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search')
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap')
]

blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    objects = models.Manager()
    published = PublishedManager()
    tags = TaggableManager()

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:post_detail", args=[self.publish.year,
                                                 self.publish.month, self.publish.day, self.slug])


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

        def __str__(self):
            return f'Comentado por {self.name} em {self.post}'

blog/forms.py
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')


class SearchForm(forms.Form):
    query = forms.CharField()

blog/views.py
from django.core.mail import send_mail
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.shortcuts import get_object_or_404, render
from django.views.generic import ListView
from taggit.models import Tag
from django.db.models import Count
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank

from .forms import EmailPostForm, CommentForm, SearchForm
from .models import Post, Comment


def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 3)  # tres postagens em cada pagina
    page = request.GET.get('page')

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        #  Se a pagina nao for um inteiro, exibe a primeira pagina
        posts = paginator.page(1)
    except EmptyPage:
        #  Se a pagina estiver fora do intervalo, exibe a ultima pagina de resultados
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/post/list.html', {'page': page, 'posts': posts, 'tag': tag})


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post, status='published', publish__year=year, publish__month=month,
                             publish__day=day)

    # Lista dos comentarios ativos para esta postagem
    comments = post.comments.filter(active=True)
    new_comment = None

    if request.method == 'POST':
        # um comentario foi postado
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Cria o objeto Commentm, mas nao o salva no banco de dados
            new_comment = comment_form.save(commit=False)
            # Atribui a postagem atual ao comentario
            new_comment.post = post
            # Salva o comentario no banco de dados
            new_comment.save()
    else:
        comment_form = CommentForm()

    # Lista de postagens semelhantes
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]

    return render(request, 'blog/post/detail.html',
                  {'post': post, 'comments': comments, 'new_comment': new_comment, 'comment_form': comment_form,
                   'similar_posts': similar_posts})


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'


def post_share(request, post_id):
    # Obtem a postagem com base no id
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False

    if request.method == 'POST':
        # Formulario foi submetido
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Campos do formulario passaram pela validacao
            cd = form.cleaned_data
            # envia o email
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} recomendou para você ler {post.title}"
            message = f"Leia {post.title} em {post_url}\n\n" f"{cd['name']}\'s comentários: {cd['comments']}"
            send_mail(subject, message, 'falcaop@gmail.com', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()

    return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'sent': sent})


def post_search(request):
    form = SearchForm()
    query = None
    results = []

    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            search_vector = SearchVector('title', weight='A') + SearchVector('body', weight='B')
            search_query = SearchQuery(query)
            results = Post.published.annotate(search=search_vector,
                                              rank=SearchRank(search_vector, search_query)).filter(
                                                  rank__gte=0.3).order_by('-rank')
    return render(request, 'blog/post/search.html', {'form': form, 'query': query, 'results': results})

blog/templates/blog/base.html
{% load blog_tags %}
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>
            {% block title%}{% endblock %}
        </title>
        <link href="{% static 'css/blog.css' %}" rel="stylesheet">
    </head>
    <body>
        <div id="content">
            {% block content %}
            {% endblock%}
        </div>
        <div id="sidebar">
            <h2>Meu Blog</h2>
            <p>Blog tutorial Django 3. Existem {% total_posts %} postagens até o momento.</p>
            <h3>Últimas postagens</h3>
                {% show_latest_posts 3 %}
            <p>
                <a href="{% url 'blog:post_feed' %}">Inscreva-se no meu feed RSS</a>
            </p>
            <h3>Postagens mais comentadas</h3>
            {% get_most_commented_posts as most_commented_posts %}
            <ul>
                {% for post in most_commented_posts %}
                    <li>
                        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </body>
</html>

blog/templates/blog/post/detail.html
{% extends 'blog/base.html' %}
{% load blog_tags %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
    <h1>{{ post.title }}</h1>
    <p class="date">
        Publicado {{ post.publish }} por {{ post.author }}
    </p>
    {{ post.body|markdown }}

    <p>
        <a href="{% url "blog:post_share" post.id %}">
            Compartilhe esse post
        </a>
    </p>

    {% with comments.count as total_comments %}
        <h2>
            {{ total_comments }} comentário{{ total_comments|pluralize }}
        </h2>
    {% endwith %}

    <h3>Posts similares</h3>
    {% for post in similar_posts %}
        <p>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </p>
    {% empty %}
        Não existem posts similares.
    {% endfor %}


    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                Comentário {{ forloop.counter }} por {{ comment.name }} em
                {{ comment.created }}
            </p>
            {{ comment.body|linebreaks }}
        </div>
        {% empty %}
            <p>Não existem comentários ainda.</p>
    {% endfor %}

    {% if new_comment %}
        <h2>Seu comentário foi adicionado</h2>
    {% else %}
        <h2>Insira um comentário</h2>
        <form method="post">
            {{ comment_form.as_p }}
            {% csrf_token %}
            <p><input type="submit" value="Inserir comentário"></p>
        </form>
    {% endif %}
{% endblock %}

blog/templates/blog/post/latest_post.html
<ul>
    {% for post in latest_posts %}
        <li>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
    {% endfor %}
</ul>

blog/templates/blog/post/list.html
{% extends 'blog/base.html' %}
{% load blog_tags %}

{% block title %}Meu Blog{% endblock %}

{% block content %}
    <h1>Meu Blog</h1>

    {% if tag %}
        <h2>Posts marcados com "{{ tag.name }}"</h2>
    {% endif  %}

    {% for post in posts %}
    <h2>
        <a href="{{ post.get_absolute_url }}">
            {{ post.title }}
        </a>
    </h2>
    <p class="tags">Tags:
        {% for tag in post.tags.all %}
            <a href="{% url "blog:post_list_by_tag" tag.slug %}">
                {{ tag.name }}
            </a>
            {% if not forloop.last %},{% endif %}
        {% endfor %}

    <p class="date">
        Publicado {{ post.publish }} por {{ post.author }}
    </p>
    {{ post.body|truncatewords_html:30 }}
    {% endfor %}

    {% include "pagination.html" with page=posts %}
{#    {% include "pagination.html" with page=page_obj %}  <!-- utilizando o ListView, altera o objeto para paginas -->#}
{% endblock %}

blog/templates/blog/post/search.html
{% extends 'blog/base.html' %}
{% load blog_tags %}

{% block title %}Pesquisa{% endblock %}

{% block content %}
    {% if query %}
        <h1>Postagens contendo "{{ query }}"</h1>
        <h3>
            {% with results.count as total_results %}
                Encontrado {{ total_results }} resultado{{ total_results|pluralize }}
            {% endwith %}
        </h3>
        {% for post in results %}
            <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
            {{ post.body|markdown|truncatewords_html:5 }}
        {% empty %}
            <p>Não foram encontrados resultados para a sua pesquisa.</p>
        {% endfor %}
        <p><a href="{% url 'blog:post_search' %}">Nova pesquisa</a></p>
    {% else %}
        <h1>Pesquisa por posts</h1>
        <form method="get">
            {{ form.as_p }}
            <input type="submit" value="Pesquisar">
        </form>
    {% endif %}
{% endblock %}

blog/templates/blog/post/share.html
{% extends 'blog/base.html' %}

{% block title %}Compartilhar um post {% endblock %}

{% block content %}
    {% if sent %}
        <h1>E-mail enviado com sucesso</h1>
        <p>
            "{{ post.title}}" foi enviado com sucesso para {{ form.cleaned_data.to }}.
        </p>
    {% else %}
        <h1>Compartilhe "{{ post.title }}" por e-mail</h1>
        <form method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Enviar e-mail">
        </form>
    {% endif %}
{% endblock %}

blog/templates/pagination.html
<div class="pagination">
    <span class="step-links">
    {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}">Anterior</a>
    {% endif %}
    <span class="current">
        Página {{ page.number }} de {{ page.paginator.num_pages }}
    </span>
    {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Próximo</a>
    {% endif %}
    </span>
</div>